language: php

php:
  - 5.5
  - 5.4
  - 5.3

install:
  - composer install

before_script:
  - mkdir build

script: ./bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - cat build/server.err.log
  - cat build/server.log
